---
# This playbook deploys the whole work machine

- name: Apply common configuration 
  hosts: main
  roles:
    - common
  tags:
    -configuration

- name: Install common tools
  hosts: main
  roles:
    - tools
  tags:
    - common tools

- name: Install jdk
  hosts: main
  roles:
    - jdk
  tags:
    - jdk

- name: Install GVM (With grails and groovy specific versions)
  hosts: main
  roles:
    - gvm
  remote_user: "{{ working_user }}"
  tags:
    - gvm
    - development

- name: Install Mysql # https://github.com/bennojoy/mysql
  hosts: databases
  roles:
    - mysql
  sudo: True
  tags:
    - mysql
    - database

- name: Install Redis # https://github.com/bennojoy/redis
  hosts: databases
  roles:
    - redis
  sudo: True
  tags:
    - redis
    - database

- name: Post configuration
  hosts: all
  roles:
    - post
  tags:
    - post
    - configuration