---

- name: delete GVM script
  file: path=/tmp/gvm-install.sh state=absent

- name: set default groovy
  shell: source ~/.gvm/bin/gvm-init.sh; gvm default groovy {{ default_groovy }} executable=/bin/bash

- name: set default grails
  shell: source ~/.gvm/bin/gvm-init.sh; gvm default grails {{ default_grails }} executable=/bin/bash  