---
# This playbook contains common plays that will be run on all nodes.

- name: Setup hosts file
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  sudo: True
  tags: 
    - hosts
    - configuration

- name: Check Pycurl is on the machine
  apt: pkg=python-pycurl
  when: ansible_os_family == "Debian"
  sudo: True