---
# This playbook contains common plays that will be run on all nodes.

- name: Setup hosts file
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  sudo: True
  tags: 
    - hosts
    - configuration

- name: Check Pycurl is on the machine
  apt: pkg=python-pycurl
  when: ansible_os_family == "Debian"
  sudo: True

- name: Set The ssh key
  copy: src={{ tb_private_key }} dest=~/.ssh/id_rsa mode=0600
  tags:
    - id_rsa
    - ssh

- name: Install Redis tunneling scripts
  template: src=tunnel.sh dest=~/tunnel.sh mode=0744
  tags:
    - script
    - tunnel

- name: Install Redis slave scripts
  template: src=slave.sh dest=~/slave.sh mode=0744
  tags:
    - script
    - slave
