---
# This playbook deploys the whole work machine

- name: Apply common configuration 
  hosts: all
  roles:
    - common
  tags:
    -configuration

- name: Install common tools
  hosts: all
  roles:
    - tools
  tags:
    - common tools

- name: Install jdk
  hosts: all
  roles:
    - jdk
  tags:
    - jdk

#- name: Install GVM (With grails and groovy specific versions)
#  hosts: all

- name: Install Mysql # https://github.com/bennojoy/mysql
  hosts: all
  roles:
    - mysql
  sudo: True
  tags:
    - mysql
    - database

#- name: Install Redis
#  hosts: all
