---
# This playbook installs GVM and working things

- name: Check user exists
  user: name={{ working_user }} state=present

- name: Download GVM script
  get_url: url=http://api.gvmtool.net dest=/tmp/gvm-install.sh mode=0744

- name: Check unzip is present
  apt: pkg=unzip
  when: ansible_os_family == "Debian"
  sudo: True

- name: Check curl is present
  apt: pkg=curl
  when: ansible_os_family == "Debian"
  sudo: True

- name: Install GVM
  command: /tmp/gvm-install.sh
  notify: delete GVM script

- name: Set GVM config
  copy: src=config dest=~/.gvm/etc/config mode=644

- name: Install Groovy versions
  shell: source ~/.gvm/bin/gvm-init.sh; gvm install groovy {{ item }} executable=/bin/bash
  with_items: groovy_versions
  notify: set default groovy
  tags: 
    - groovy

- name: Install Grails versions
  shell: source ~/.gvm/bin/gvm-init.sh; gvm install grails {{ item }} executable=/bin/bash
  with_items: grails_versions
  notify: set default grails
  tags: 
    - grails